---
title: "Flagship descriptives"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# preamble
rm(list = ls())
library(haven)
library(tidyverse)
library(ggplot2)
library(janitor)
library(cowplot)
library(reshape2)
library(scales)
library(stringr)
setwd("~/EGVPI/flagship/analysis")
theme_set(theme_cowplot())

# open
STATIC <- read_dta("data/Static CTF oct30.dta") %>% filter(country_group == 0)
DYN <- read_dta("data/dynamic CTF Oct 30.dta") %>% filter(country_group == 0)
REG <- read_dta("data/regional classification.dta") %>% select(-economy)
WDI <- read_csv("data/wdi_gdp_pop.csv", show_col_types = F)
CLIAR2FLAG <- readxl::read_excel("data/CLIARtoFLAGSHIP.xlsx", sheet = "Sheet2")

# merge with regional classifications
STATIC <- left_join(x = STATIC, y = REG, by = c("country_code")) 
DYN <- left_join(x = DYN, y = REG, by = c("country_code"))

# remove accents
STATIC$country_name <- stringi::stri_trans_general(STATIC$country_name, id = "latin-ascii")

# move Bermuda to LAC and remove North America
STATIC$region[STATIC$country_code == "BMU"] <- "Latin America & Caribbean"
STATIC <- STATIC %>% filter(region != "North America")
DYN$region[DYN$country_code == "BMU"] <- "Latin America & Caribbean"
DYN <- DYN %>% filter(region != "North America")

# aggregate static into flagship concepts
STATIC <- STATIC %>% melt(id.vars = c("country_name", "country_code", "country_group",
                                      "region", "incomegroup", "lendingcategory"))
CLIAR2FLAG$variable <- tolower(CLIAR2FLAG$variable)
STATIC$value_num <- ifelse(STATIC$value == "NA", NA, as.numeric(STATIC$value))
CLIAR2FLAG <- CLIAR2FLAG %>% rename(org_cap = `Organizational Capacity`,
                      people = `People`,
                      money = `Money`,
                      systems = `Systems`,
                      dmp = `Decision Making processes`) %>% 
  mutate(org_cap = ifelse(is.na(org_cap), 0, org_cap),
         people = ifelse(is.na(people), 0, people),
         money = ifelse(is.na(money), 0, money),
         systems = ifelse(is.na(systems), 0, systems),
         dmp = ifelse(is.na(dmp), 0, dmp))
STATIC <- left_join(x = STATIC, y = CLIAR2FLAG, by = c("variable"))

# filter and reshape WDI
WDI <- WDI %>% filter(`Series Name` == "GDP per capita (constant 2015 US$)")
WDI$`Series Name`[WDI$`Series Name` == "GDP per capita (constant 2015 US$)"] <- "gdppercap_constant2015"
WDI <- WDI %>% select(-`Series Name`, -`Series Code`) %>% melt(id.vars = c("Country Name", "Country Code")) %>% 
  rename(gdppercap_constant2015 = value, year = variable) 
WDI$year <- as.numeric(str_extract(WDI$year, pattern = "^\\d{4}"))
WDI <- WDI %>% filter(year >= 2013)

### aggregate and combine the flagship concepts ----

# org cap
n_orgcap <- STATIC %>% distinct(variable, org_cap) %>% summarise(n = sum(org_cap, na.rm = T)) %>% unlist() 
org_cap <- STATIC %>%
  filter(!grepl(variable, pattern = "_avg") & org_cap == 1) %>% 
  group_by(country_code, region, lendingcategory) %>% 
  summarise(n_orgcap_notmissing = sum(!is.na(value)),
            mean_orgcap = mean(value, na.rm = T)) %>% arrange(desc(mean_orgcap))
org_cap$n_orgcap <- n_orgcap

# people 
n_people <- STATIC %>% distinct(variable, people) %>% summarise(n = sum(people, na.rm = T)) %>% unlist() 
people <- STATIC %>%
  filter(!grepl(variable, pattern = "_avg") & people == 1) %>% 
  group_by(country_code, region, lendingcategory) %>% 
  summarise(n_people_notmissing = sum(!is.na(value)),
            mean_people = mean(value, na.rm = T)) %>% arrange(desc(mean_people))
people$n_people <- n_people

# money
n_money <- STATIC %>% distinct(variable, money) %>% summarise(n = sum(money, na.rm = T)) %>% unlist() 
money <- STATIC %>%
  filter(!grepl(variable, pattern = "_avg") & money == 1) %>% 
  group_by(country_code, region, lendingcategory) %>% 
  summarise(n_money_notmissing = sum(!is.na(value)),
            mean_money = mean(value, na.rm = T)) %>% arrange(desc(mean_money))
money$n_money <- n_money

# systems 
n_systems <- STATIC %>% distinct(variable, systems) %>% summarise(n = sum(systems, na.rm = T)) %>% unlist() 
systems <- STATIC %>%
  filter(!grepl(variable, pattern = "_avg") & systems == 1) %>% 
  group_by(country_code, region, lendingcategory) %>% 
  summarise(n_systems_notmissing = sum(!is.na(value)),
            mean_systems = mean(value, na.rm = T)) %>% arrange(desc(mean_systems))
systems$n_systems <- n_systems

# decision-making processes
n_dmp <- STATIC %>% distinct(variable, dmp) %>% summarise(n = sum(dmp, na.rm = T)) %>% unlist() 
dmp <- STATIC %>%
  filter(!grepl(variable, pattern = "_avg") & dmp == 1) %>% 
  group_by(country_code, region, lendingcategory) %>% 
  summarise(n_dmp_notmissing = sum(!is.na(value)),
            mean_dmp = mean(value, na.rm = T)) %>% arrange(desc(mean_dmp))
dmp$n_dmp <- n_dmp

# combine
FLAG <- left_join(x = org_cap, y = people, by = c("country_code", "region", "lendingcategory"))
FLAG <- left_join(x = FLAG, y = money, by = c("country_code", "region", "lendingcategory"))
FLAG <- left_join(x = FLAG, y = systems, by = c("country_code", "region", "lendingcategory"))
FLAG <- left_join(x = FLAG, y = dmp, by = c("country_code", "region", "lendingcategory"))

# create percents
FLAG <- FLAG %>% mutate(perc_orgcap = n_orgcap_notmissing / n_orgcap)
FLAG <- FLAG %>% mutate(perc_people = n_people_notmissing / n_people)
FLAG <- FLAG %>% mutate(perc_money = n_money_notmissing / n_money)
FLAG <- FLAG %>% mutate(perc_systems = n_systems_notmissing / n_systems)
FLAG <- FLAG %>% mutate(perc_dmp = n_dmp_notmissing / n_dmp)

### combine STATIC with WDI ----

# merge
WDI$gdppercap_constant2015[WDI$gdppercap_constant2015 == ".."] <- NA
WDI$gdppercap_constant2015 <- as.numeric(WDI$gdppercap_constant2015)
WDI <- WDI %>% select(-`Country Name`) %>% rename(country_code = `Country Code`)
WDI <- WDI %>% group_by(country_code) %>% 
  mutate(latest_year = max(year[!is.na(gdppercap_constant2015)])) %>% 
  filter(latest_year != -Inf) # latest available year by country
WDI <- WDI %>% filter(year == latest_year) %>% distinct(country_code, year, gdppercap_constant2015)
FLAG <- left_join(x = FLAG, y = WDI, by = c("country_code")) 

### functions ----

# percent observed
percent_observed <- function(data, x_var, title_string, x_string){

data %>% ggplot(aes(x = {{ x_var }})) + geom_histogram(bins = 30) + 
  geom_vline(aes(xintercept = mean({{ x_var }}), color = "orangered")) + 
  labs(x = x_string,
       y = "Frequency",
       title = title_string) +
  theme(legend.position = "none")
  
}

# variation across regions
regional_variation <- function(data, var, title_label){
  
  data %>% filter(perc_orgcap > 0.5) %>%  group_by(region) %>% 
    mutate(code_max = ifelse({{ var }}== max({{ var }}, na.rm = T), country_code, NA),
           code_min = ifelse({{ var }} == min({{ var }}, na.rm = T), country_code, NA)) %>%
    fill(code_max, code_min, .direction = "updown") %>%
    summarise(mean_var = mean({{ var }}, na.rm = T),
              bar_max = ifelse(!is.na(mean_var), max({{ var }}, na.rm = T), NA),
              bar_min = ifelse(!is.na(mean_var), min({{ var }}, na.rm = T), NA),
              code_max = unique(code_max),
              code_min = unique(code_min)) %>% 
    ggplot(aes(x = region, y = mean_var)) + 
    geom_bar(stat = "identity") +
    geom_errorbar(aes(ymin = bar_min, ymax = bar_max), width = 0.1) +
    geom_text(aes(label = code_max, y = bar_max), vjust = -0.75) +
    geom_text(aes(label = code_min, y = bar_min), vjust = 1.5) +
    scale_x_discrete(labels = wrap_format(14)) + 
    labs(x = "Region", y = "Value", title = title_label) +
    scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2)) +
    theme(axis.text.x = element_text(size = 8))
  
}

# static scatter plot of CLIAR vs Bank's goals
scatter_bankgoals <- function(data, x_var, y_var, title_string, x_string, y_string){
  
  data %>% ggplot(aes(x = {{ x_var }}, y = log({{ y_var }}),
                      group = region, color = region)) + 
  geom_point() + 
  labs(x = x_string, y = y_string,
       title = title_string,
       color = "Region") +
  scale_y_continuous(limits = c(5, 12), breaks = seq(5, 12, 1)) + 
  scale_x_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.1)) + 
  theme(legend.position = "bottom",
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 8))
  
}

```

# Proportion of variables observed
```{r observed, echo = FALSE, message = FALSE, output = TRUE, warning = FALSE, fig.width = 6, fig.height = 4}

# organizational capacity
percent_observed(data = FLAG, x_var = perc_orgcap,
                 x_string = "Percent of 'organizational capacity'\n variables observed per country",
                 title_string =  paste0("Money", " (", n_orgcap, " variables)"))

# people
percent_observed(data = FLAG, x_var = perc_people,
                 x_string = "Percent of 'people'\n variables observed per country",
                 title_string =  paste0("Money", " (", n_people, " variables)"))

# money 
percent_observed(data = FLAG, x_var = perc_money,
                 x_string = "Percent of 'money'\n variables observed per country",
                 title_string = paste0("Money", " (", n_money, " variables)"))

# systems
percent_observed(data = FLAG, x_var = perc_money,
                 x_string = "Percent of 'systems'\n variables observed per country",
                 title_string = paste0("Systems", " (", n_systems, " variables)"))

# dmp
percent_observed(data = FLAG, x_var = perc_dmp,
                 x_string = "Percent of 'decision-making processes'\n variables observed per country",
                 title_string = paste0("Decision-making processes", " (", n_dmp, " variables)"))

```

# Variation across regions
```{r regionalvar, echo = FALSE, message = FALSE, output = TRUE, warning = FALSE, fig.width = 6, fig.height = 4}

# org cap
regional_variation(data = FLAG[FLAG$perc_orgcap > 0.50,],
                   var = mean_orgcap,
                   title = "'Organizational capacity' across regions")

# people
regional_variation(data = FLAG[FLAG$perc_people > 0.50,],
                   var = mean_people,
                   title = "'People' across regions")

# money
regional_variation(data = FLAG[FLAG$perc_money > 0.50,],
                   var = mean_money,
                   title = "'Money' across regions")

# systems
regional_variation(data = FLAG[FLAG$perc_systems > 0.50,],
                   var = mean_systems,
                   title = "'Systems' across regions")

# dmp
regional_variation(data = FLAG[FLAG$perc_dmp > 0.50,],
                   var = mean_dmp,
                   title = "'Decision-making processes' across regions")

```

# Institutions and GDP per capita
```{r gdppercapita, echo = FALSE, message = FALSE, output = TRUE, warning = FALSE, fig.width = 6, fig.height = 4}

# organizational capacity 
scatter_bankgoals(data = FLAG[FLAG$perc_orgcap > 0.50,],
                  x_var = mean_orgcap, y_var = gdppercap_constant2015,
                  title_string = "GDP per capita and organizational capacity",
                  x = "Average 'organizational capacity' value",
                  y = "GDP per capita\n constant 2015 USD (log)")

# people
scatter_bankgoals(data = FLAG[FLAG$perc_people > 0.50,],
                  x_var = mean_people, y_var = gdppercap_constant2015,
                  title_string = "GDP per capita and 'people'",
                  x = "Average 'people' value", 
                  y = "GDP per capita\n constant 2015 USD (log)")

# money
scatter_bankgoals(data = FLAG[FLAG$perc_money > 0.50,],
                  x_var = mean_money, y_var = gdppercap_constant2015,
                  title_string = "GDP per capita and 'money'",
                  x = "Average 'money' value", 
                  y = "GDP per capita\n constant 2015 USD (log)")

# systems
scatter_bankgoals(data = FLAG[FLAG$perc_systems > 0.50,],
                  x_var = mean_systems, y_var = gdppercap_constant2015,
                  title_string = "GDP per capita and 'systems'",
                  x = "Average 'systems' value", 
                  y = "GDP per capita\n constant 2015 USD (log)")

# dmp
scatter_bankgoals(data = FLAG[FLAG$perc_dmp > 0.50,],
                  x_var = mean_dmp, y_var = gdppercap_constant2015,
                  title_string = "GDP per capita and 'decision-making processes'",
                  x = "Average 'decision-making processes' value", 
                  y = "GDP per capita\n constant 2015 USD (log)")

# orgcap vs dmp
FLAG %>% ggplot(aes(x = mean_dmp, y = mean_orgcap, 
                    color = region, group = region)) + geom_point() + 
  labs(color = "Region", x = "Average 'decision-making processes' value",
       y = "Average 'organizational\n capacity' value",
       title = "Org. capacity vs decision-making processes") + 
  theme(legend.position = "bottom",
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 8))


```






